spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/medicalsystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&useGeneratedKeys=true&keyProperty="ID"
      username: root
      password: 123456
  application:
    name: userService
  cloud:
    nacos:
      server-addr: localhost:8848

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    virtual-host: /

server:
  port: 8082
#  redis:
#    host: localhost
#    port: 6379




